### ISSUE TITLE
Composer 2.0 PSR-4 compatability

### ISSUE THREAD

**Issue by jamie-accessfertility** [JustSteveKing/eloquent-log-driver#1]
Running composer install/update while running composer ^2.0 and package version ^1.0 will cause:

`Class JustSteveKing\EloquentLogDriver\Src\Loggers\EloquentLogger located in /vendor/juststeveking/eloquent-log-driver/src\Loggers\EloquentLogger.php does not comply with psr-4 autoloading standard. Skipping.`

Updating the namespace within that class from - 
`namespace JustSteveKing\EloquentLogDriver\Logger;`

to

`namespace JustSteveKing\EloquentLogDriver\Loggers;` will fix the issue.

Thanks

**Comment by JustSteveKing** [comment]
Hey!

I will add this to my list, but if you would like to submit a PR to guarantee it getting solved soon I'm happy to accept one!

**Comment by jamie-accessfertility** [comment]
Thanks JustSteveKing!

Theres another issue when trying to upgrade to Laravel 8 too which I don't mind fixing if that's okay.

Thanks again.

**Comment by JustSteveKing** [comment]
Feel free!!

I actually only built this package originally for the project you're working on ...
